feature(api): add toolings end point to list supported terminologies
b2ihealthcare/snow-owl pull request #1023
Opened 2022-05-24 12:57 UTC by AAAlinaaa

2022-05-24 13:09 UTC, apeteri commented
Please add an example response JSON here.

2022-05-24 20:04 UTC, cmark requested changes

2022-05-24 20:04 UTC, cmark commented on core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/admin/ConfiguredToolingsRestService.java
> +	public @ResponseBody Promise<Collection<Terminology>> toolings() {
On REST interfaces, please always use `List` or `SortedSet` types to ensure consistent order.

2022-05-24 20:04 UTC, cmark commented on core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/admin/ConfiguredToolingsRestService.java
> +	public @ResponseBody Promise<Collection<Terminology>> toolings() {
Promise wrapping is unnecessary.

2022-05-25 08:23 UTC, AAAlinaaa commented
[
  {
    "name": "Logical Observation Identifiers Names and Codes",
    "toolingId": "loinc",
    "effectiveTimeSupported": true,
    "terminologyComponents": [
      "com.b2international.snowowl.loinc.core.domain.LoincConcept"
    ],
    "dependencies": []
  }
]

2022-05-25 09:19 UTC, cmark commented
> [ { "name": "Logical Observation Identifiers Names and Codes", "toolingId": "loinc", "effectiveTimeSupported": true, "terminologyComponents": [ "com.b2international.snowowl.loinc.core.domain.LoincConcept" ], "dependencies": [] } ]

That is too much information exposed from our internal tooling registry. The response should look like this:
```
{
  "toolings": [
    "snomed",
    "loinc",
    "icd10"
  ]
}
```

2022-05-26 15:18 UTC, cmark requested changes

2022-05-26 15:18 UTC, cmark commented on core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/admin/ConfiguredToolingsRestService.java
> +	public @ResponseBody ResponseEntity<List<String>> toolings() {
No need for the ResponseEntity wrapping, but we need a wrapping object instead see the example JSON I have sent you.

2022-05-27 08:09 UTC, cmark approved these changes
LGTM!

2022-05-27 08:09 UTC, merged