docs: Fix and improve simple load SNOMED CT distribution page
b2ihealthcare/snow-owl pull request #1093
Opened 2022-11-29 17:07 UTC by apeteri

https://snowowl.atlassian.net/browse/SO-5569

2022-11-30 12:41 UTC, cmark requested changes

2022-11-30 12:41 UTC, cmark commented on docs/getting_started/codesystems.md
> +    "defaultRefsetModuleId": "900000000000012004",
Please remove user-facing/application-specific configuration settings from this example.

2022-12-05 16:05 UTC, cmark approved these changes
🥓

2022-12-09 10:11 UTC, nagyo approved these changes
LGTM!

2022-12-09 10:27 UTC, merged