Use ubuntu as base image for docker containers
b2ihealthcare/snow-owl pull request #1100
Opened 2023-01-10 14:29 UTC by nagyo

- simplified builder stage
- introduced new label ci.passed
- rename client url labels to be consistent
- more secure file ownership settings
- use tini to init

2023-01-10 15:14 UTC, cmark requested changes

2023-01-10 15:14 UTC, cmark commented on docker/Dockerfile
> +ARG MAC_CLIENT_URL=""
Do we really need the client urls here?

2023-01-19 15:15 UTC, nagyo commented on docker/Dockerfile
> +ARG MAC_CLIENT_URL=""
Nope, good catch :thumbsup:

2023-01-19 15:29 UTC, cmark approved these changes
🥓

2023-01-19 15:53 UTC, apeteri approved these changes
👍

2023-01-19 15:55 UTC, merged