SO-5690: Add missing fields to SnomedComponent builders
b2ihealthcare/snow-owl pull request #1126
Opened 2023-03-20 09:55 UTC by AAAlinaaa

2023-03-20 10:07 UTC, cmark requested changes
🥓 
Could you please add a test case that breaks without these? Thanks!

2023-03-21 08:39 UTC, cmark requested changes

2023-03-21 08:39 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/versioning/SnomedVersioningApiTest.java
> +		assertTrue(conceptBeforeVersioning.getTotal() == 1);
Use `assertThat(conceptBeforeVersioning.getTotal()).isEqualTo(1)` instead.

2023-03-21 08:39 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/versioning/SnomedVersioningApiTest.java
> +		assertTrue(conceptAfterVersioning.getTotal() == 1);
And here as well.

2023-03-21 08:39 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/versioning/SnomedVersioningApiTest.java
> +		String conceptId = createConcept(new CodeSystemURI(INT_CODESYSTEM), SnomedRestFixtures.childUnderRootWithDefaults());
Extract the URI to a local variable.

2023-03-21 12:10 UTC, cmark approved these changes
LGTM!

2023-03-21 12:10 UTC, merged

2023-04-11 13:05 UTC, apeteri commented
https://github.com/b2ihealthcare/snow-owl/pull/905 adds the missing builder method calls to concept documents, but the rest still needs to be ported to 8.x.