MRCM range validation rule fix
b2ihealthcare/snow-owl pull request #1180
Opened 2023-06-27 09:47 UTC by AAAlinaaa

2023-06-27 10:13 UTC, apeteri requested changes

2023-06-27 10:13 UTC, apeteri commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +			clause = rangeClause.substring(0, rangeClause.indexOf('|')).strip();
The parsed representation above could be put to good use to remove all human-readable labels from the expression. I'm afraid the string cutting logic will break the moment someone adds a range clause with a refinement or filter, eg. `<< 404684003 |Clinical finding| {{ C definitionStatus = primitive }}`.

2023-06-27 10:19 UTC, apeteri approved these changes
I'm going to approve as if we want to keep index-based querying (especially in the case of relationship snippets on OWL axiom members) for performance reasons, range expressions are not allowed to get more complex than the constructs currently supported.

2023-06-28 15:10 UTC, nagyo approved these changes
I'm also not entirely happy with manually parsing ECL expressions where there would be a better programmatic approach, but I'll accept the fix, otherwise, every validation run would fail if a malformed expression is present.

2023-06-28 15:10 UTC, merged