feat(snomed.datastore): Allow using searchAfter when the number of...
b2ihealthcare/snow-owl pull request #1187
Opened 2023-07-10 16:35 UTC by apeteri

...requested items is larger than the currently configured maximum result window.

2023-07-11 07:38 UTC, nagyo approved these changes
LGTM!

2023-07-11 15:33 UTC, cmark requested changes

2023-07-11 15:33 UTC, cmark commented on commons/com.b2international.index.tests/src/com/b2international/index/StreamTest.java
> +			.limit(pageSize)
I think the purpose here was to actually page through the results with the page size of `1000`, now we are going to fetch it in one go, right?

2023-07-11 15:33 UTC, cmark commented on commons/com.b2international.index/src/com/b2international/index/es/EsDocumentSearcher.java
> +		} if (isLiveStreaming) {
This block looks a bit weird.

2023-07-12 07:03 UTC, cmark approved these changes
🥓

2023-07-12 07:04 UTC, merged