fix(fhir): Remove CapabilityStatement and its "read" interaction from...
b2ihealthcare/snow-owl pull request #1247
Opened 2023-11-22 16:44 UTC by apeteri

...the list of supported resources and operations over the FHIR REST API. The statement belonging to Snow Owl as an instance is still served via the "metadata" interaction.

2023-11-22 17:02 UTC, cmark requested changes

2023-11-22 17:02 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirMetadataController.java
> -@Tag(description="CapabilityStatement", name = FhirApiConfig.CAPABILITY_STATEMENT, extensions = {
The Tag itself is required to categorize the controller and its endpoints into an API group, could you please add it back?

2023-11-23 08:45 UTC, apeteri commented on fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirMetadataController.java
> -@Tag(description="CapabilityStatement", name = FhirApiConfig.CAPABILITY_STATEMENT, extensions = {
Done in https://github.com/b2ihealthcare/snow-owl/pull/1247/commits/40ad88672b2170e03b39273c7d0b7a6327bec465.

2023-11-24 09:06 UTC, cmark approved these changes
🥓

2023-12-05 13:04 UTC, nagyo approved these changes
LGTM! 🍏

2023-12-05 13:04 UTC, merged