SO-6087 Duplicate description revisions after upgrade
b2ihealthcare/snow-owl pull request #1280
Opened 2024-04-24 13:37 UTC by AAAlinaaa

2024-04-30 07:26 UTC, cmark requested changes

2024-04-30 07:26 UTC, cmark commented on commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
> +					stagedObjects.put(objectId, changed(newDocument, diff, commit));
Additional tests were requested on the sibling PR #1281, please add that test case to this branch as well.

2024-04-30 07:26 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionUpgradeTest.java
> +				System.err.println(node);
Remove debug lines.

2024-04-30 07:26 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionUpgradeTest.java
> +			hits.forEach(node -> System.err.println(node));
From here as well.

2024-04-30 07:26 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/ext/SnomedExtensionUpgradeTest.java
> +			hits.forEach(node -> System.err.println(node));
And from here.

2024-04-30 07:46 UTC, apeteri approved these changes
👍 once Márk's comments are addressed.

2024-05-03 07:31 UTC, cmark requested changes

2024-05-03 07:31 UTC, cmark commented on commons/com.b2international.index.tests/src/com/b2international/index/revision/SingleDocumentRevisionIndexTest.java
> +		assertEquals(data, staging.getNewObject(RevisionData.class, STORAGE_KEY1));
Perform an assert here that the isCommit flag did not change because there were no changes, so the original is still uncommitable.

2024-05-03 07:31 UTC, cmark commented on commons/com.b2international.index.tests/src/com/b2international/index/revision/SingleDocumentRevisionIndexTest.java
> +		assertEquals(updatedData, staging.getNewObject(RevisionData.class, STORAGE_KEY1));
Perform an assert here that the isCommit flag did change to true due to changes in the underlying revision.

2024-05-07 14:44 UTC, cmark approved these changes
🥓

2024-05-07 20:15 UTC, apeteri approved these changes

2024-05-08 07:00 UTC, merged