SO-6087 Avoid creating new revision in absence of changes
b2ihealthcare/snow-owl pull request #1281
Opened 2024-04-26 12:25 UTC by AAAlinaaa

2024-04-30 07:24 UTC, cmark requested changes

2024-04-30 07:24 UTC, cmark commented on commons/com.b2international.index/src/com/b2international/index/revision/StagingArea.java
> +					stagedObjects.put(objectId, changed(newDocument, diff, commit));
I think we can create a very minimal test case for this in the index layer module.
1. Use the RevisionData fixture class
2. Start a commit by creating a staging area
3. Add an object to the staging area with commit=false
4. Then add an object to the staging area with commit=true with no changes (assert after this that the staging area did not change)
5. Then add an object to the staging area with commit=true with changes (assert after this that the staging area did change)

2024-04-30 07:45 UTC, apeteri approved these changes
LGTM!

2024-05-02 11:32 UTC, cmark requested changes

2024-05-02 11:32 UTC, cmark commented on commons/com.b2international.index.tests/src/com/b2international/index/revision/SingleDocumentRevisionIndexTest.java
> +		staging.stageNew(data, false);
The implemented test case is a bit different than the one I described, please take a look again.

2024-05-07 07:40 UTC, cmark requested changes

2024-05-07 07:40 UTC, cmark commented on commons/com.b2international.index.tests/src/com/b2international/index/revision/SingleDocumentRevisionIndexTest.java
> +		assertEquals(updatedData, staging.getNewObject(RevisionData.class, STORAGE_KEY1));
Are you sure this is the right outcome here? According to the implementation, this should give us a changed object rather than a new object.

2024-05-07 15:27 UTC, cmark approved these changes
🥓

2024-05-07 20:16 UTC, apeteri reviewed
💯

2024-05-08 07:00 UTC, merged