SO-5952: Windows 11 UI - Menu item icons
b2ihealthcare/snow-owl pull request #1300
Opened 2024-06-19 14:44 UTC by adamfilep

2024-06-19 16:07 UTC, apeteri approved these changes
👍

2024-06-19 20:12 UTC, cmark requested changes

2024-06-19 20:12 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/util/PlatformUtil.java
> +        return System.getProperty("os.name").equals("Windows 11");
PLease fix the indentation.

2024-06-20 14:20 UTC, cmark approved these changes
🥓

2024-06-20 14:20 UTC, merged