Fix delta import commit notification
b2ihealthcare/snow-owl pull request #198
Opened 2018-02-16 12:54 UTC by zoliMolnar

This pull request fixes the "no commit notification" after delta import is finished bug.

2018-02-19 10:39 UTC, nagyo requested changes

2018-02-19 10:39 UTC, nagyo commented on snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/japi/branches/BranchTimestampUpdateTest.java
> +	public void testHeadTimestampUpdateAfterImporting() {
Please move this to com.b2international.snowowl.snomed.api.rest.io.SnomedImportApiTest. There is no need to have this separately from all the other import tests.

2018-02-19 10:39 UTC, nagyo commented on snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/japi/branches/BranchTimestampUpdateTest.java
> +	public void testHeadTimestampUpdateAfterImporting() {
You'll have everything you need available in that package, both the import archive and all the supporting methods. In the end you can remove this class and the duplicate archive as well.

2018-02-19 10:39 UTC, nagyo commented on snomed/com.b2international.snowowl.snomed.importer.rf2/src/com/b2international/snowowl/snomed/importer/rf2/util/ImportUtil.java
> +			final SnomedCompositeImporter importer = new SnomedCompositeImporter(IMPORT_LOGGER, repositoryState, importContext, importers, ComponentImportUnit.ORDERING);
Why have you changed these three lines?

2018-02-22 14:38 UTC, cmark approved these changes

2018-02-22 14:38 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/io/SnomedImportApiTest.java
> +		assertThat(branchBeforeImport.baseTimestamp(), not(equalTo(branchAfterImport.headTimestamp())));
Use a shorter version of assertion to increase readability: `assertNotEquals(branchAfterImport.baseTimestamp(), branchAfterImport.headTimestamp())`.

2018-02-26 14:09 UTC, closed without merging