SO-2586 Compare results exporter logic on platform
b2ihealthcare/snow-owl pull request #224
Opened 2018-04-27 12:18 UTC by tamasmucs

2018-05-04 08:23 UTC, cmark requested changes

2018-05-04 08:23 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/exporter/CompareResultsDsvExporter.java
> + *******************************************************************************/
⚠️ Invalid license header!

2018-05-04 08:23 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/exporter/CompareResultsDsvExporter.java
> +package com.b2international.snowowl.datastore.exporter;
Move this to the `com.b2international.snowowl.core.compare` package in this bundle.

2018-05-04 08:23 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/exporter/CompareResultsDsvExporter.java
> +					.then((CollectionResource<IComponent> newComponents) -> {
If you wait for the result of a fetch with `getSync()` then it is an anti-pattern to put logic into a `then` callback. This logic should be executed after the `getSync()` call.
Also, moving the `write.write()` logic out of the then callback will eliminate the need for the `try-catch` block and will propagate the exception properly to the caller of the `export` function.

2018-05-04 08:23 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/exporter/CompareResultsDsvExporter.java
> +						.then((CollectionResource<IComponent> changedComponentsOnBaseBranch) -> {
Same unnecessary `then()` chaining here. Use traditional synchronous execution flow instead of the async flow.

2018-05-04 08:23 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/exporter/CompareResultsDsvExporter.java
> +					comparisonResultsOfThisChunk.forEach(t -> {
Use standard forEach loop instead of forEach with lambda and remove the `try-catch` block.

2018-05-04 08:23 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/exporter/CompareResultsDsvExporter.java
> +						deletedComponents.forEach(component -> {
Same `forEach` to `for` loop change here.

2018-05-04 08:23 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/exporter/CompareResultsDsvExporter.java
> +					.then((CollectionResource<IComponent> deletedComponents) -> {
Same unnecessary `then()` callback.

2018-05-07 11:32 UTC, tamasmucs commented
exception handling is now propagated to caller, and unnecessary asynchronous flow logic with ```then``` has been eliminated.

2018-05-17 08:33 UTC, cmark approved these changes
LGTM!

2018-05-17 08:34 UTC, merged