SO-2918: Implement mrcm relationship concept set definition rules
b2ihealthcare/snow-owl pull request #226
Opened 2018-05-02 12:27 UTC by AAAlinaaa

2018-05-04 08:31 UTC, cmark requested changes

2018-05-04 08:31 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/META-INF/MANIFEST.MF
> + com.b2international.commons
This is already a dependency via `snowowl.core`, please remove it.

2018-05-04 08:31 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/japi/io/SnomedRefSetDSVExportTest.java
> +				.flatMap(concept -> concept.getRelationships().stream().map(relationship -> relationship.getTypeId() + Ecl.EQUAL + relationship.getDestinationId()))
The format of a relationship MRCM domain should be moved to the `SnomedConstraintDocument` class.
For example: `SnomedConstraintDocument.relationshipDomainOf(typeId, destinationId)`.

2018-05-07 11:44 UTC, apeteri requested changes

2018-05-07 11:44 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/japi/io/SnomedRefSetDSVExportTest.java
> +				.flatMap(concept -> concept.getRelationships().stream().map(relationship -> SnomedConstraintDocument.relationshipDomainOf(relationship.getTypeId(), relationship.getTypeId())))
In `SnomedConstraintDocument.relationshipDomainOf(...)`, the second parameter should be the relationship's destination ID.

2018-05-22 08:23 UTC, apeteri commented
Changes included in #236, closing PR.

2018-05-22 08:23 UTC, closed without merging