SO-2989: Whitelist refresh problem
b2ihealthcare/snow-owl pull request #229
Opened 2018-05-04 08:32 UTC by zoliMolnar

2018-05-04 08:37 UTC, cmark requested changes

2018-05-04 08:37 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationRepositoryContext.java
> +	private final Set<String> ruleIdsAffectedByDeletion = Sets.newHashSet();
Convert this field to a local variable in the commit method.

2018-05-17 07:43 UTC, cmark commented
LGTM!

2018-05-17 07:43 UTC, cmark approved these changes

2018-05-17 07:43 UTC, merged

2018-05-17 07:54 UTC, zoliMolnar commented
Thank you!