Validation issues view improvements
b2ihealthcare/snow-owl pull request #243
Opened 2018-06-21 15:06 UTC by norban

https://snowowl.atlassian.net/browse/SO-3097

2018-06-26 10:23 UTC, cmark requested changes

2018-06-26 10:23 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/ValidateRequest.java
> +	@SuppressWarnings("unlikely-arg-type")
🛑 Fix Java warnings of `unlikely-arg-type` instead of suppressing them!

2018-06-26 10:23 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/whitelist/ValidationWhiteListSearchRequest.java
> +		TERM, REPORTER
`REPORTER` option key is unused! Please add support for filtering by reporter only.

2018-06-26 10:23 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/whitelist/ValidationWhiteListSearchRequest.java
> +	private Expression toComponentIdQuery(final Collection<String> componentIds) {
It seems that this method is not being called by the search request. Remove it or call it from the appropriate place.

2018-06-27 08:01 UTC, norban commented
Requested changes have been applied

2018-06-27 12:02 UTC, cmark approved these changes
LGTM!

2018-06-27 12:04 UTC, merged