SO-3125: Resolve validation performance issues
b2ihealthcare/snow-owl pull request #246
Opened 2018-06-29 07:29 UTC by zoliMolnar

https://snowowl.atlassian.net/browse/SO-3125

This pull request resolves validation performances by utilizing the jobs API, to async run multiple validation rules.

2018-06-29 08:38 UTC, cmark requested changes

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore.server.tests/src/com/b2international/snowowl/core/validation/ValidationThreadPoolTest.java
> + * Copyright 2011-2018 B2i Healthcare Pte Ltd, http://b2i.sg
New files should indicate current year as starting year in the license header.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore.server.tests/src/com/b2international/snowowl/core/validation/ValidationThreadPoolTest.java
> +	private static final int MAXIMUM_AMOUNT_OF_RUNNING_EXPENSIVE_JOBS = 1;
Provide this as configuration to the `ValidationThreadPool` class so deployments with more computational power (CPU, RAM, ES cluster nodes) can increase the number of expensive jobs. This would be useful for the other `CheckType`s as well.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore.server.tests/src/com/b2international/snowowl/core/validation/ValidationThreadPoolTest.java
> +		final ValidationThreadPool pool = new ValidationThreadPool(VALIDATION_THREAD_COUNT);
Test fixture initialization should go into a `@Before` method, please convert common variables to fields and initialize them in that method.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore.server.tests/src/com/b2international/snowowl/core/validation/ValidationThreadPoolTest.java
> +			validationPromises.add(pool.submit(CheckType.NORMAL, createValidatableRunnable(CheckType.FAST, manager)));
⚠️ NORMAL vs FAST!

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore.server.tests/src/com/b2international/snowowl/core/validation/ValidationThreadPoolTest.java
> +				Thread.sleep(500);
Would be nice to configure this hardcoded 500 ms timeout value based on the given `CheckType`, just to simulate the cost more accurately.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore.server.tests/src/com/b2international/snowowl/core/validation/ValidationThreadPoolTest.java
> +				e.printStackTrace();
Wrap all non-`RuntimeException`s into `RuntimeException`s and let them broke the tests.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationJob.java
> +	public ValidationJob(Object family, Runnable runnable) {
Add a null check to `family` and `runnable` arguments

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationJob.java
> +		runnable.run();
Add catch clause for `OperationCancelledException` and return CANCEL_STATUS.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationRuleSchedulingRule.java
> + * Copyright 2011-2018 B2i Healthcare Pte Ltd, http://b2i.sg
⚠️ Fix license year!

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationJob.java
> + * Copyright 2011-2018 B2i Healthcare Pte Ltd, http://b2i.sg
⚠️ Fix license year!

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationJob.java
> +		return (this.family == null || family == null) ? false : this.family.equals(family);
Use `java.util.Objects.equals()`.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationRuleSchedulingRule.java
> +	private final String uniqueRuleId;
What is `uniqueRuleId`? This should be either just `ruleId` or just `id`. IDs are meant to be **unique**.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationRuleSchedulingRule.java
> +		int hash = 17;
Use `Objects.hash(args)` correctly, where you pass all values directly to the function and not one-by-one.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationRuleSchedulingRule.java
> +		return uniqueRuleId;
Add `checkType` to `toString()`

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationThreadPool.java
> +			public void done(IJobChangeEvent event) {
Missing `@Override` annotation.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationThreadPool.java
> +		final Promise<Object> isRuleDonePromise = new Promise<>();
Rename `isRuleDonePromise` to just `promise`.

2018-06-29 08:38 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/rule/ValidationRuleCreateRequest.java
> +	private CheckType checkType;
Add `NotNull` annotation or default value `CheckType.NORMAL`.

2018-07-04 09:44 UTC, cmark requested changes

2018-07-04 09:44 UTC, cmark commented on core/com.b2international.snowowl.datastore.server.tests/src/com/b2international/snowowl/core/validation/ValidationThreadPoolTest.java
> +		System.out.println();
Remove `println` calls. If you would like to separate the log output of the test cases then use a `JUnit Rule` like this class: `com.b2international.snowowl.test.commons.TestMethodNameRule`.

2018-07-04 09:44 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationBootstrap.java
> +			// TODO calculate these based on systems overall strength
Move these to actual `snowowl_config.yml` configuration values.

2018-07-04 09:44 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationJob.java
> +		return Objects.equal(this.family, family);
Use `java.util.Objects`, please.

2018-07-04 09:44 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationRuleSchedulingRule.java
>  		return hash;
Just return the value computed by the Objects.hash method, like this:

```
@Override
public int hashCode() {
    return Objects.hash(checkType, id, maxConcurrentJobs, maxConcurrentExpensiveJobs);
}
```

2018-07-04 09:44 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/internal/validation/ValidationRuleSchedulingRule.java
> +		return id + " " + checkType.getName();
Use `String.format()` method.

2018-07-04 11:48 UTC, cmark approved these changes
LGTM!

2018-07-04 11:48 UTC, merged

2018-07-04 13:42 UTC, zoliMolnar commented
Thank you!