Rest API dependency version bump
b2ihealthcare/snow-owl pull request #252
Opened 2018-08-01 09:56 UTC by zoliMolnar

2018-08-01 12:09 UTC, apeteri requested changes

2018-08-01 12:09 UTC, apeteri commented on core/com.b2international.snowowl.api.rest/src/com/b2international/snowowl/api/rest/SnowowlApiConfig.java
> +@PropertySource(value="classpath:com/b2international/snowowl/api/rest/service_configuration.properties")
Do the &commat;`Value` annotations work in the code below (and in other classes which use it), are you seeing the expected values from the property file in Swagger's API info section? If not, this snippet is also needed:

```
@Bean
public static PropertySourcesPlaceholderConfigurer ppc() throws IOException {
    return new PropertySourcesPlaceholderConfigurer();
}
```

2018-08-01 12:09 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/config/SnomedSecurityConfig.java
> -@EnableGlobalMethodSecurity(securedEnabled=true, proxyTargetClass=true)
Note: This annotation corresponds to this bit in the .xml version:  `<global-method-security secured-annotations="enabled" proxy-target-class="true" />`, the corresponding feature is documented here: http://www.baeldung.com/spring-security-method-security

It got removed there, and it got removed here; I don't remember using &commat;`Secured` annotations on any method at the moment, so this _might_  be OK. Otherwise put it back in! 😄

2018-08-01 12:09 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/config/SnomedSecurityConfig.java
> -	public AuthenticationManager authenticationManagerBean() throws Exception {
This method should be kept! As I understand it, the flow of execution goes something like this:

- This configuration class inherits from `WebSecurityConfigurerAdapter`, which allows it to mess around with the `AuthenticationManagerBuilder` in the method above, before the manager is built;
- We set the provider on the builder to `authenticationProvider`;
- We should also expose the built `AuthenticationManager`, but if this dummy override is not present, it will not be available.

The reason is that the superclass does not have a &commat;`Bean` annotation on this method. See `WebSecurityConfigurerAdapter#authenticationManagerBean()`'s javadoc.

2018-08-01 13:28 UTC, zoliMolnar commented on core/com.b2international.snowowl.api.rest/src/com/b2international/snowowl/api/rest/SnowowlApiConfig.java
> +@PropertySource(value="classpath:com/b2international/snowowl/api/rest/service_configuration.properties")
The @Value annotations work as intended

2018-08-01 13:32 UTC, zoliMolnar commented on snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/config/SnomedSecurityConfig.java
> -@EnableGlobalMethodSecurity(securedEnabled=true, proxyTargetClass=true)
There are no methods which use @secured annotations so I've removed them, should I still add them back in any case?

2018-08-01 13:40 UTC, apeteri commented on core/com.b2international.snowowl.api.rest/src/com/b2international/snowowl/api/rest/SnowowlApiConfig.java
> +@PropertySource(value="classpath:com/b2international/snowowl/api/rest/service_configuration.properties")
(A random GitHub user just got mentioned; talking about Java annotations in comments is hard. Use `&commat;` to escape the &commat; symbol.)

2018-08-02 08:16 UTC, apeteri approved these changes

2018-08-02 08:20 UTC, zoliMolnar commented
Thank you!

2018-08-02 08:20 UTC, zoliMolnar commented on core/com.b2international.snowowl.api.rest/src/com/b2international/snowowl/api/rest/SnowowlApiConfig.java
> +@PropertySource(value="classpath:com/b2international/snowowl/api/rest/service_configuration.properties")
I'll keep that in mind for future references, thank you.

2018-08-02 08:26 UTC, merged