Bump virgo server version to 3.7.2
b2ihealthcare/snow-owl pull request #253
Opened 2018-08-02 09:58 UTC by zoliMolnar

2018-08-06 09:54 UTC, cmark requested changes

2018-08-06 09:54 UTC, cmark commented on releng/com.b2international.snowowl.server.update/assembly/common/bin/dmk.sh
> -        JAVA_OPTS="$JAVA_OPTS \
This was our custom default JVM configuration, please bring it back. Also check the other files as well, again!

2018-08-08 12:55 UTC, apeteri requested changes

2018-08-08 12:55 UTC, apeteri commented on releng/com.b2international.snowowl.server.update/assembly/common/configuration/tomcat-server.xml
> +    <Connector address="127.0.0.1" port="8080"
This will make the non-HTTPS port listen on the local interface only; please change the `address` value to `0.0.0.0`.

2018-08-08 13:09 UTC, apeteri approved these changes
👍

2018-08-08 13:18 UTC, zoliMolnar commented
Thanks

2018-08-08 13:35 UTC, cmark approved these changes
LGTM!

2018-08-08 14:19 UTC, nagyo approved these changes
👍

2018-08-08 14:22 UTC, merged