SO-3239: Add inboundRelationships expand option to concept search and get requests
b2ihealthcare/snow-owl pull request #267
Opened 2018-09-20 09:07 UTC by zoliMolnar

2018-09-24 08:32 UTC, cmark requested changes

2018-09-24 08:32 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedConceptConverter.java
> +		final SnomedRelationships inboundRelationships = SnomedRequests.prepareSearchRelationship()
Please, add support for filtering inbound relationships by `typeId` and `sourceId`.

2018-09-25 11:32 UTC, cmark requested changes

2018-09-25 11:32 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/components/SnomedConceptApiTest.java
> +	//@Test
Please add these tests back to the test suite. Thank you!

2018-09-25 11:44 UTC, cmark requested changes

2018-09-25 11:44 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedConcept.java
Javadoc is missing from `setInboundRelationships` method.

2018-09-25 11:44 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedConcept.java
> +	 *
Remove unnecessary spaces/newlines.

2018-09-25 12:08 UTC, cmark approved these changes
LGTM!

2018-09-25 12:08 UTC, merged

2018-09-25 12:09 UTC, zoliMolnar commented
Thank you!