SO-3188: Add option for unpublished validation
b2ihealthcare/snow-owl pull request #271
Opened 2018-09-21 15:14 UTC by norban

2018-09-24 08:53 UTC, cmark requested changes

2018-09-24 08:53 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/ValidateRequest.java
> +	public void setFilterOptions(Map<String, Object> filterOptions) {
Reduce visibility to `package private`.

2018-09-24 08:53 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/ValidateRequestBuilder.java
> +	public ValidateRequestBuilder setFilterOptions(Map<String, Object> filterOptions) {
`ruleParameters` would be a better name for this request parameter, rename it pls.

2018-09-24 08:53 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/eval/GroovyScriptValidationRuleEvaluator.java
> -	public List<ComponentIdentifier> eval(BranchContext context, ValidationRule rule) throws Exception {
Keep the `BranchContext` as a separate parameter to the scripts.

2018-09-24 08:53 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/ruleSnomedCommon1.groovy
> +	if (params.containsKey(EffectiveTimes.UNSET_EFFECTIVE_TIME_LABEL)) {
Use a different parameter name than `EffectiveTimes.UNSET_EFFECTIVE_TIME_LABEL` for Unpublished only validation

2018-09-24 10:23 UTC, norban commented
Requested changes have been applied

2018-09-25 11:35 UTC, cmark requested changes

2018-09-25 11:35 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/ValidateRequestBuilder.java
> +	public ValidateRequestBuilder setFilterOptions(Map<String, Object> ruleParameters) {
Please change the method name here and the parameter name in the ValidateRequest class as well.

2018-09-25 12:11 UTC, cmark approved these changes
LGTM!

2018-09-25 12:15 UTC, merged

2018-09-25 12:18 UTC, zoliMolnar commented
Thank you!