SO-3300: Fix simple type refset header issues
b2ihealthcare/snow-owl pull request #276
Opened 2018-10-30 14:28 UTC by zoliMolnar

This pull request fixes shifting headers in case of simple type refset dsv export, if any of the optional flags are toggled (includeDescriptionId, includeRelationshipId, includeInactiveMembers)

2018-11-05 09:57 UTC, cmark requested changes

2018-11-05 09:57 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.exporter.server/src/com/b2international/snowowl/snomed/exporter/server/dsv/SnomedSimpleTypeRefSetDSVExporter.java
> +		lineSeparator = System.getProperty("line.separator");
Extract this value as constant.

2018-11-06 09:45 UTC, norban commented
Requested change has been applied.

2018-11-06 09:46 UTC, cmark approved these changes
LGTM!

2018-11-06 09:47 UTC, merged