Multi-repository versioning support
b2ihealthcare/snow-owl pull request #286
Opened 2018-12-03 09:28 UTC by norban

2018-12-03 09:57 UTC, cmark requested changes

2018-12-03 09:57 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/merge/MergeService.java
> +	Merge enqueue(String source, String target, String commitMessage, String reviewId, String parentLockDescription);
Rename `parentLockDescription` to `parentLockContext`.

2018-12-03 09:57 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/CoreTerminologyBroker.java
> +		final List<String> affectedCodeSystems = Lists.newArrayList();
Read and cache all dependencies on first access.

2018-12-03 09:57 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/CodeSystemEntry.java
> +	public List<String> getAffectedCodeSystems() {
Rename to `getDependencies()`.

2018-12-03 09:57 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/request/Locks.java
> +		this(context, User.SYSTEM.getUsername(), DatastoreLockContextDescriptions.SYNCHRONIZE, parentLockDescription, firstBranch, nextBranches);
If possible pass the actual username instead of the system user.

2018-12-03 09:57 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/request/version/CodeSystemVersionCreateRequest.java
> +		acquireLocks(context, user, versioningManagersByCodeSystem.keySet());
Always release locks in a `try...finally` block.

2018-12-03 09:57 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/request/version/CodeSystemVersionCreateRequest.java
> +		CoreTerminologyBroker.getInstance().getAffectedCodeSystemsForTeminology(baseCodeSystem.getTerminologyComponentId())
Try to use the new `CodeSystemEntry.getDependencies()` method.

2018-12-03 10:32 UTC, cmark requested changes

2018-12-03 10:32 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/CodeSystemEntry.java
> +	public List<String> getAffectedCodeSystems() {
Or rename it to `getDependenciesAndSelf()` and the method should return a `java.util.SortedSet<E>`.

2018-12-03 16:02 UTC, cmark requested changes

2018-12-03 16:02 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/CoreTerminologyBroker.java
> +				if (id.equals(terminologyId)) {
How about reading all of them at once and just the one we actually need?

2018-12-03 16:02 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/CodeSystemEntry.java
> +		return new TreeSet<String>(affectedCodeSystems);
It would be great to return an immutable SortedSet.

2018-12-03 16:02 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/CodeSystemEntry.java
> +		return new TreeSet<String>(affectedCodeSystems);
Also return the SortedSet directly from the `CoreTerminologyBroker` method.

2018-12-03 16:02 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/request/CreateMergeRequestBuilder.java
> +	public CreateMergeRequestBuilder setparentLockContext(String parentLockContext) {
🛑 Method name should be written in camelCase.

2018-12-04 08:50 UTC, cmark requested changes

2018-12-04 08:50 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/CoreTerminologyBroker.java
> +		if (!TERMINOLOGY_ID_TO_SHORTNAMES_CACHE.containsKey(terminologyId)) {
🛑 Still not a properly initialized cache!

The if expression should not rely on the existence of the given `terminologyId` key.

2018-12-04 08:50 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/CodeSystemEntry.java
> +		Set<String> affectedCodeSystems = Sets.newHashSet(CoreTerminologyBroker.getInstance().getAffectedCodeSystemsForTeminology(terminologyComponentId));
🛑 This method still creates too many unnecessary objects to return a `SortedSet` of Strings.

2018-12-04 08:50 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/request/version/CodeSystemVersionCreateRequest.java
> +		return Boolean.TRUE;
Move this inside the `try` block.

2018-12-04 08:50 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/request/version/CodeSystemVersionCreateRequest.java
> +		CoreTerminologyBroker.getInstance().getAffectedCodeSystemsForTeminology(baseCodeSystem.getTerminologyComponentId())
Or the new `CodeSystemEntry.getDependenciesAndSelf()` method.

2018-12-04 08:50 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/request/version/CodeSystemVersionCreateRequest.java
> +			.execute(context.service(IEventBus.class))
Execute the search code system request synchronously on the current context.

2018-12-04 10:52 UTC, AAAlinaaa commented
Requested changes have been applied.

2018-12-04 16:31 UTC, cmark requested changes

2018-12-04 16:31 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/CoreTerminologyBroker.java
> +			final List<String> affectedCodeSystems = Lists.newArrayList();
Remove this unnecessary `ArrayList` instance.

2018-12-04 16:31 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/CoreTerminologyBroker.java
> +		Preconditions.checkNotNull(terminologyId, "terminologyId");
Unnecessary null check. `Map.containsKey()` will return false and the `null` value will be reported by the `IllegalArgumentException`. I suggest using `Preconditions.checkArgument(boolean, String)`.

2018-12-04 16:31 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/CodeSystemEntry.java
> +	public String getRelativeBranchPath(String relativeTo) {
⚠️ Documentation is missing for this method.

2018-12-04 16:31 UTC, cmark commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/CodeSystemEntry.java
> +		com.google.common.collect.ImmutableSortedSet.Builder<String> affectedCodeSystems = ImmutableSortedSet.naturalOrder();
⚠️ Unnecessary FQN here.

2018-12-04 17:34 UTC, cmark approved these changes

2018-12-04 17:34 UTC, merged