SO-3434: Remove formatting of exported query expression
b2ihealthcare/snow-owl pull request #304
Opened 2019-02-14 16:17 UTC by AAAlinaaa

2019-02-15 10:33 UTC, cmark requested changes

2019-02-15 10:33 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/exporter/Rf2RefSetExporter.java
> +							query = query.replace("\r", " ");
A simplified regex would be better here to reduce multiple control characters into a single space: `replaceAll("[\r\n]+", " ")`.

2019-02-15 10:33 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/exporter/Rf2RefSetExporter.java
> +							query = query.replace("\r", " ");
Also, move the logic to the `toColumn()` method.

2019-02-15 10:34 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/exporter/Rf2RefSetExporter.java
> +							query = query.replace("\r", " ");
The first replacement could be `query = query.replace("\r\n", " ");`
The way it currently is, CRLF sequences get replaced by two spaces, one for `\r` and one for `\n`.

2019-02-15 10:38 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/rf2/exporter/Rf2RefSetExporter.java
> +							query = query.replace("\r", " ");
Another option is to use Guava's  `CharMatcher` for all replacements:
```
property = CharMatcher.breakingWhitespace().replaceFrom(query, ' ');
```

2019-02-27 07:41 UTC, cmark approved these changes
LGTM!

2019-02-27 07:41 UTC, merged