Classification API improvements
b2ihealthcare/snow-owl pull request #359
Opened 2019-06-04 12:35 UTC by zoliMolnar

2019-06-04 16:36 UTC, apeteri requested changes

2019-06-04 16:36 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedClassificationRestService.java
> +		} else if (expand.contains("relationsip")) {
```suggestion
		} else if (expand.contains("relationship(")) {
```

The typo definitely needs fixing, the opening parenthesis ensures that this is the end of an expand option, it is just a bonus.

2019-06-06 08:51 UTC, cmark approved these changes
LGTM!

2019-06-06 08:54 UTC, apeteri approved these changes

2019-06-06 09:25 UTC, merged