SO-3740: Filter for unpublished members in snomed_common_rule_4
b2ihealthcare/snow-owl pull request #394
Opened 2019-09-05 16:23 UTC by AAAlinaaa

2019-09-11 07:27 UTC, cmark requested changes

2019-09-11 07:27 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/ruleSnomedCommon4.groovy
> +	def unpublishedLangueMembers = SnomedRequests.prepareSearchMember()
Rename `unpublishedLangueMembers` to `descriptionsIdsWithUnpublishedLanguageMembers`.

2019-09-11 07:27 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/ruleSnomedCommon4.groovy
> +				.all()
You can safely set the limit to `unpublishedLangueMembers.size()` instead of requesting `all()`.

2019-09-23 09:09 UTC, nagyo approved these changes
LGTM!

2019-09-23 09:10 UTC, merged