Fix reference set member id duplication
b2ihealthcare/snow-owl pull request #412
Opened 2019-10-10 11:50 UTC by zoliMolnar

2019-10-10 12:51 UTC, apeteri requested changes

2019-10-10 12:51 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.api.rest.tests/src/com/b2international/snowowl/snomed/api/rest/components/SnomedRefSetMemberApiTest.java
> +	//@Test
Is this test no longer working as a result of the PR?

2019-10-10 12:51 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.api.rest/src/com/b2international/snowowl/snomed/api/rest/SnomedReferenceSetMemberRestService.java
> +		UUID.fromString(id);
Is this method call here to check if the format is correct? Please add a comment if so.

2019-10-10 12:51 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/IdRequest.java
> +						final Set<String> userRequestedIds = Sets.newHashSet(Iterables.concat(coreComponentIds, refsetMemberIds));
This line is always going to be concatenating an empty set to a useful (hopefully non-empty) set -- I'd be tempted to add a special case for `ComponentCategory.SET_MEMBER`, even if it breaks equal handling of categories slightly 🙁

2019-10-10 13:51 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/IdRequest.java
> +							recorder.register(coreComponentIds);
It turned out that we need this separation due to this line, so the original form is OK as well.

2019-10-10 14:30 UTC, apeteri approved these changes

2019-10-15 15:29 UTC, cmark approved these changes
LGTM!

2019-10-15 15:29 UTC, merged