Implement access controlled requests
b2ihealthcare/snow-owl pull request #413
Opened 2019-10-14 09:14 UTC by zoliMolnar

2019-10-21 08:56 UTC, apeteri commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/commit/CommitInfoGetRequest.java
> +		return new Permission(Permission.BROWSE, Permission.ALL);
Just adding a note here: the required permission might be dependent on the (repository) context the request is executed in. As an example, the user might gain access to the commit history of one repository, but be denied when trying to do the same for another.

2019-10-21 09:21 UTC, apeteri requested changes
There are 4 big categories that were repeated in requests:

* read = `Permissions.BROWSE` + `Permissions.ALL`
* write = `Permissions.EDIT` + `Permissions.ALL`
* read SCT = `Permissions.BROWSE` + `SnomedDatastoreActivator.REPOSITORY_UUID`
* write SCT = `Permissions.EDIT` + `SnomedDatastoreActivator.REPOSITORY_UUID`

...in addition to the occasional import/export special permissions. I wouldn't mind if a hierarchy of small interfaces would be added instead of repeating the `Permission` constructor all over; there are 89 occurrences just in this PR and it is very hard to keep track of all of them. Something like this:

```java
public interface ReadAction extends AccessControl {
    @Override
    public default Permission getPermission() {
        return new Permission(Permission.BROWSE, Permission.ALL);
    }
}
```

2019-10-21 09:21 UTC, apeteri commented on cis/com.b2international.snowowl.snomed.cis/src/com/b2international/snowowl/snomed/cis/request/SnomedIdentifierGetRequest.java
> +
You added the two import statements here, but no permission. Will the identifier requests require authorization?

2019-10-21 09:21 UTC, apeteri commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/terminologyregistry/core/request/CodeSystemCreateRequest.java
> +		return new Permission(Permission.EDIT, repositoryUuid);
Is the "resource" of the `Permission.EDIT` operation a code system or a repository?

2019-10-21 09:21 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclEvaluationRequest.java
> +		return new Permission(Permission.BROWSE, SnomedDatastoreActivator.REPOSITORY_UUID);
👀 Looks like it's a repository

2019-10-21 09:21 UTC, apeteri commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/events/CreateReviewRequest.java
> +		return new Permission(Permission.BROWSE, Permission.ALL);
⚠️ This is a "write" request, yet it only requires `Permission.BROWSE` permissions.

2019-10-21 09:21 UTC, apeteri commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/events/ReadConceptChangesRequest.java
> +		return new Permission(Permission.EDIT, Permission.ALL);
⚠️ This is a "read" request, yet it requires `Permission.EDIT` permissions.

2019-10-21 09:21 UTC, apeteri commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/events/ReadReviewRequest.java
> +		return new Permission(Permission.EDIT, Permission.ALL);
⚠️ This is a "read" request, yet it requires Permission.EDIT permissions.

2019-10-21 09:21 UTC, apeteri commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/core/validation/ValidateRequest.java
> +		return new Permission(Permission.BROWSE, Permission.ALL);
Operation is debatable. A validation will "write" a bunch of stuff, and remove the earlier set of results, so it might need `Permission.EDIT`.

2019-10-21 09:21 UTC, apeteri commented on core/com.b2international.snowowl.datastore/src/com/b2international/snowowl/datastore/request/version/CodeSystemVersionCreateRequest.java
> +		// XXX - is all repositories correct?
It is not, but we don't have any alternative at the moment - see comment above.

2019-10-21 09:21 UTC, apeteri commented on core/com.b2international.snowowl.identity/src/com/b2international/snowowl/identity/request/UserGetRequest.java
> + * Copyright 2017-2019 B2i Healthcare Pte Ltd, http://b2i.sg
No access control for this request?

2019-10-21 09:21 UTC, apeteri commented on core/com.b2international.snowowl.identity/src/com/b2international/snowowl/identity/request/UserSearchRequest.java
> + * Copyright 2017-2019 B2i Healthcare Pte Ltd, http://b2i.sg
No access control for this request either?

2019-10-21 09:21 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptUpdateRequest.java
> +
Is the permission missing here?

I can imagine two approaches:

* pull permissions up to superclasses, ie. set `Permissions.EDIT` on `SnomedComponentUpdateRequest`, also make the method final
* push down permissions to each leaf

2019-10-21 09:21 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationCreateRequest.java
> +		return new Permission(Permission.BROWSE, SnomedDatastoreActivator.REPOSITORY_UUID);
⚠️ This request should require `Permission.EDIT` permission

2019-10-24 08:19 UTC, cmark approved these changes
LGTM!

2019-10-24 08:20 UTC, apeteri approved these changes

2019-10-24 08:23 UTC, merged