SO-4100: Extra concept non-current member fix
b2ihealthcare/snow-owl pull request #584
Opened 2020-06-10 13:00 UTC by adeakgabi

When inactivating-reactivating and inactivating the concept again, there will be only a single inactivation reason member on each component.
When reactivating the concept its descriptions with "Concept non-current" indicator will be deleted.

2020-06-10 21:10 UTC, cmark requested changes

2020-06-10 21:10 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ComponentInactivationChangeProcessor.java
> +			for (Hits<SnomedRefSetMemberIndexEntry> hits : searcher.scroll(Query.select(SnomedRefSetMemberIndexEntry.class)
Do we actually need all indicators when there is an inactivated Concept? This can be really costly. 
I suggest limiting the number of loaded indicators to the actually used set (descriptions of inactivated concepts and only active inactivation members).
Also, any duplicates that are present in the dataset will be omitted by the code, since this HashMap can only reference a single member by the referenced component, while a referenced component can have more than one indicator (active, inactive, potential duplicates).

2020-06-15 10:25 UTC, cmark requested changes

2020-06-15 10:25 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ComponentInactivationChangeProcessor.java
> +					.filter(SnomedRefSetMemberIndexEntry.Expressions.referenceSetId(Concepts.REFSET_DESCRIPTION_INACTIVITY_INDICATOR))
Can we restrict the number loaded members to just the necessary set of members?
How about restricting to the actually read values, descriptions in the transaction?

2020-06-17 10:04 UTC, cmark approved these changes
LGTM!

2020-06-17 10:11 UTC, apeteri approved these changes
👍

2020-06-17 10:14 UTC, merged