SO-4219: Comparing large sets times out
b2ihealthcare/snow-owl pull request #637
Opened 2020-08-14 13:16 UTC by molnarlaura

2020-08-15 11:12 UTC, cmark requested changes

2020-08-15 11:12 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptMapSearchRequestEvaluator.java
> +						.filterByIds(targetIds)
Missing `all()` or explicit `setLimit` call.

2020-08-17 06:15 UTC, molnarlaura commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptMapSearchRequestEvaluator.java
> +						.filterByIds(targetIds)
Done

2020-08-18 09:48 UTC, cmark approved these changes

2020-08-18 09:48 UTC, merged