SO-4280: Enforce new rules to determine definition status of a concept:
b2ihealthcare/snow-owl pull request #663
Opened 2020-09-17 15:23 UTC by AAAlinaaa

* If a concept only has equivalent class axioms make it defined
* If a concept only has sub class axioms make it primitive
* If a concept contains a mixture make it primitive as well

2020-09-17 15:29 UTC, apeteri requested changes
Please re-formulate the expression so that the definition status only becomes `FULLY_DEFINED` if - ignoring any GCI axioms - all remaining axioms are of type "equivalent classes". 0 axioms of such kind should still result in `PRIMITIVE` status, which doesn't happen with the code in its current form.

2020-09-18 13:16 UTC, apeteri requested changes

2020-09-18 13:16 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedOWLAxiomHelper.java
>  				.filter(expression -> !Strings.isNullOrEmpty(expression))
Filter GCI axioms here, not in the create or update requests. They don't have a say in the concept's suggested definition status, but should be going through when creating or updating a SNOMED CT concept, just as before.

Or did they cause some other problem?

2020-09-22 09:38 UTC, cmark commented
Putting this to on hold. Not sure about the proper logic here, need more information to decide.

2026-07-03 14:21 UTC, closed without merging