SO-4303: include Value Set members in FSN/PT switch
b2ihealthcare/snow-owl pull request #688
Opened 2020-10-07 22:49 UTC by kovacstomi

2020-10-13 19:57 UTC, cmark requested changes, later dismissed

2020-10-13 19:57 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/domain/Concept.java
> +	public String getPreferredTerm() {
Not sure if it is a good idea to call this term a preferred term. If you would like to rename it, then let's use FHIR phrases, like designation or display here. `getDisplay` or `getDisplayTerm` would be alternatives I can think of.

2020-10-13 19:57 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedDescription.java
> +	public Description.Type getCommonDescriptionType() {
There are multiple issues with this method:
* Introduces a new JSON property in the serialized form of this representation class
* Returns UNKNOWN for synonym subtypes
* Returns UNKNOWN for partially loaded descriptions
Let's chat, why do you need this new enum type and where are you going to use it.

2020-10-17 12:35 UTC, cmark commented
@kovacstomi Could you please fix the conflict and also the spurious javadoc reported by LGTM? Thanks!

2020-10-19 09:41 UTC, nagyo approved these changes
LGTM!

2020-10-19 09:44 UTC, merged