SO-4622: Support recreation of existing version at version create
b2ihealthcare/snow-owl pull request #746
Opened 2021-01-22 18:06 UTC by AAAlinaaa

2021-01-26 09:07 UTC, cmark requested changes

2021-01-26 09:07 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/version/CodeSystemVersionCreateRequest.java
> +	private boolean deleteBranch(Branch branch, String repositoryId, ServiceProvider context) {
Request method signature order convention is `context` first, then rest of the parameters in abstract to more specific order.

2021-01-26 09:07 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/version/CodeSystemVersionCreateRequest.java
> +					if (!force || !deleteBranch(branch, repositoryId, context)) {
We can be smarter by moving the force flag up and detecting force recreation earlier and skipping one fetch entirely.

2021-01-26 09:07 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/version/CodeSystemVersionCreateRequestBuilder.java
> +	private Boolean force;
Set it `false` by default here.

2021-01-26 09:07 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/versioning/SnomedVersioningApiTest.java
> +		createVersion(SNOMED_SHORT_NAME, "SnomedVersioningApiTest", getNextAvailableEffectiveDateAsString(SNOMED_SHORT_NAME), true).statusCode(201);
It would be better to create an isolated test case and not one that depends on another. Test cases should not rely on each other.

2021-01-26 15:48 UTC, cmark requested changes

2021-01-26 15:48 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/version/VersioningRequest.java
> +				context.delete(version);
No need to explicitly delete the version, the ID will be the same so the document will be overwritten.

2021-01-26 15:48 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/versioning/SnomedVersioningApiTest.java
> +
Please include a component change in the new force recreated version and check the absence and presence before and after the force create version request.

2021-01-31 08:38 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/version/VersioningRequest.java
> +				context.delete(version);
Hmm, this is not true at the moment, so we will keep it.

2021-02-03 20:31 UTC, apeteri approved these changes
👍

2021-02-03 20:32 UTC, apeteri commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/version/CodeSystemVersionCreateRequest.java
> +					if (!force || !deleteBranch(branch, repositoryId, context)) {
This has been smartened 💡

2021-02-04 09:32 UTC, cmark approved these changes
LGTM!

2021-02-04 09:36 UTC, apeteri approved these changes

2021-02-04 09:39 UTC, merged