SO-4712: Commit classification changes in commit water mark low batches
b2ihealthcare/snow-owl pull request #805
Opened 2021-05-04 12:22 UTC by AAAlinaaa

2021-05-05 17:34 UTC, cmark requested changes

2021-05-05 17:34 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
> -import com.b2international.snowowl.snomed.reasoner.domain.*;
Revert this change please and configure your IDE to use wildcard import when the number of import statements is greater than or equal to `5`.

2021-05-05 17:34 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
> +		if (EffectiveTimes.UNSET_EFFECTIVE_TIME == resultTimeStamp) {
Why `EffectiveTimes.UNSET_EFFECTIVE_TIME`? That constant is being used for other purposes. Please use `Commit.NO_COMMIT_TIMESTAMP` instead.

2021-05-06 10:03 UTC, apeteri requested changes

2021-05-06 10:03 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
> +		final List<RequestBuilder<TransactionContext, ?>> bulkRequestBuilder = Lists.newArrayList();
You can make this change a lot smaller by skipping all `List<RequestBuilder<TransactionContext, ?>>` changes and `(RequestBuilder<TransactionContext, ?>)` casts below, if you keep the `BulkRequestBuilder` type here, then call `build` on it and ask for its request list via `BulkRequest#getRequests` for the partitioning step.

2021-05-06 16:39 UTC, AAAlinaaa commented
Closed in favor of https://github.com/b2ihealthcare/snow-owl/pull/809

2021-05-06 16:39 UTC, closed without merging