Improvement/SO-3158_search_parameter_support
b2ihealthcare/snow-owl pull request #806
Opened 2021-05-06 07:33 UTC by bbanfai

Please look at the changes committed to the _ext_ repository on the same named branch.

2021-05-06 15:12 UTC, cmark requested changes
In general, looks okay. I think it is a bit too much for supporting several FHIR search and filter parameters as we have only going to implement three resources (CodeSystem, ValueSet and ConceptMap). For 7.x the implementation looks reasonable and we can keep it, but I think we might need an additional rework on 8.x after the core resource model redesign. Now that I have a bit more understanding of the implementation we can talk about the next steps.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirFilterParameter.java
> + * @since 7.14
Since tags should be `7.17.0`.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirFilterParameter.java
> +	public FhirFilterParameter(FhirUriFilterParameterDefinition supportedFilterParameter, Collection<String> values) {
If the preferred way of building parameters like this is through a builder, then please restrict access to the class' constructor.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirFilterParameter.java
> +			Set<String> supportedValues = filterParameterDefinition.getSupportedValues();
⚠️ Potential NPE.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirParameter.java
> +	protected FhirUriParameterDefinition parameterDefinition;
There is a getter to access this field, reduce visibility to `private`. And also make this field `final`.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirParameter.java
> +	protected Collection<String> values;
There is a getter to access this field, reduce visibility to `private`. And also make this field `final`.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirParameter.java
> +		protected Collection<String> values = Sets.newHashSet();
For performance purposes, it is recommended to initialize fields with `null` values first (unless you use constants) and later instantiate them with an initial value (with reduced capacity). A single `newHashSet()` creates a `HashMap` with capacity of `16`. Alternatively, it is recommended to use `ImmutableList/Set` Builders to allocated just the right amount of space for the collection, but I suggest the use of the first best practice.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirSearchParameter.java
> +	private SearchRequestParameterModifier modifier;
Make this field `final`.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirSearchParameter.java
> +public class FhirSearchParameter extends FhirParameter {
If this is a leaf class then make it `final`.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirUriFilterParameterDefinition.java
> +	private FhirFilterParameterKey requestParameterKey;
Move fields above the constructor and make them `final`.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirUriFilterParameterDefinition.java
> +		super(requestParameterKey, FhirFilterParameterKey.valueOf(requestParameterKey).getParameterType(), isMultipleValuesSupported, supportedValues);
```suggestion
		super(requestParameterKey, FhirFilterParameterKey.fromRequestParameter(requestParameterKey).getParameterType(), isMultipleValuesSupported, supportedValues);
```

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirUriSearchParameterDefinition.java
> +	private Set<String> supportedModifiers = Sets.newHashSet();
Unnecessary initialization of `field`. Make the field `final`.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirUriSearchParameterDefinition.java
> +		this.supportedModifiers = Sets.newHashSet(supportedModifiers);
Use `Collections3.toImmutableSet()`.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/RawRequestParameter.java
> +package com.b2international.snowowl.fhir.core.search;
⚠️ Missing license.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/RawRequestParameter.java
> +public class RawRequestParameter {
If this is a leaf class make it `final`.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/RawRequestParameter.java
> +	private Collection<String> values;
Make these fields `final`.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/RawRequestParameter.java
> +	public RawRequestParameter(@NotEmpty String parameterKey, Collection<String> parameterValues) {
Not sure if this annotation works here as intended.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/tests/endpoints/codesystem/CodeSystemRestTest.java
> +	//Invalid ID parameter
Unnecessary comment.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/tests/endpoints/codesystem/CodeSystemRestTest.java
> +	//Id parameters
Same here. Test method name should give the reader enough context to understand the test case.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/tests/endpoints/codesystem/CodeSystemRestTest.java
> +	//Name parameter
Same here.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/tests/endpoints/codesystem/CodeSystemRestTest.java
> +	//Multiple name parameter
Same here.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/tests/endpoints/codesystem/CodeSystemRestTest.java
>  	//Fully detailed SNOMED CT code system
Same here.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/tests/filter/FhirRequestParameterTest.java
> +	//Raw unprocessed parameter
I suggest including this extra information in the test method's name.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/tests/filter/FhirRequestParameterTest.java
> +	//URI -> Raw unprocessed parameter
Same here. The test method name is just too generic.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest.tests/src/com/b2international/snowowl/fhir/tests/filter/FhirRequestParameterTest.java
> +import static org.hamcrest.MatcherAssert.assertThat;
Use assertj's Assertions. They give much better error messages and readability.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/BaseFhirResourceRestService.java
> +		FhirUriParameterManager parameterManager = FhirUriParameterManager.createFor(getModelClass());
Should we cache this instance somewhere? Each request creates its own instance, which can lead to too much garbage.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirCodeSystemRestService.java
> +		Pair<Set<FhirFilterParameter>, Set<FhirSearchParameter>> requestParameters = processParameters(parameters);
My problem with this approach is the missing opportunity to document this reliably on the REST endpoints directly. Since the endpoints aggregate the parameters into a single MultiValueMap there is no place for OpenApi declarations. This way the Swagger UI (or RapiDoc) won't be able to document them individually and clients will need to enter their parameters manually, which works but it is prone to error. Other FHIR API implementations offer dedicated fields and documentation for each supported field directly on the API endpoint. It would be great to offer something like in our server as well.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirUriParameterManager.java
> +			if (!p.getParameterDefinition().isMultipleValuesSupported() && p.getValues().size() > 1) {
Cases like this could be handled easily via Spring's built-in REST API declaration annotations.

2021-05-06 15:12 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirUriParameterManager.java
> +		return Pair.of(filterParameters, searchParameters);
A dedicated return type would be better than the `Pair` tuple model.

2021-05-10 11:36 UTC, bbanfai commented on fhir/com.b2international.snowowl.fhir.rest/src/com/b2international/snowowl/fhir/rest/FhirCodeSystemRestService.java
> +		Pair<Set<FhirFilterParameter>, Set<FhirSearchParameter>> requestParameters = processParameters(parameters);
Given the complexity and the different ways to accomplish multi-values parameters, not to mention the optional prefixes and modifiers I am not sure how to accomplish this with dedicated fields.

2021-05-10 11:53 UTC, bbanfai commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirUriParameterManager.java
> +			if (!p.getParameterDefinition().isMultipleValuesSupported() && p.getValues().size() > 1) {
Let's consider this after this PR.

2021-05-10 11:54 UTC, bbanfai commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirUriParameterManager.java
> +		return Pair.of(filterParameters, searchParameters);
Let's consider this change after this PR - we might need to change this return type anyways.

2021-05-17 13:23 UTC, cmark requested changes
Tests are failing. Could you please fix them before merging? 🙇

2021-05-17 13:23 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/provider/CodeSystemApiProvider.java
> +		return codeSystemVersion.getUri().getCodeSystem() + "/" + codeSystemVersion.getUri().getPath();
Why not `codeSystemVersion.getUri().toString()`?

2021-05-17 13:23 UTC, cmark commented on fhir/com.b2international.snowowl.fhir.core/src/com/b2international/snowowl/fhir/core/search/FhirUriParameterDefinition.java
> +				try {
How about a single big try-catch block around the entire switch case statement instead of 4 small ones?

2021-05-18 08:35 UTC, cmark approved these changes
LGTM!

2021-05-18 08:35 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.fhir/src/com/b2international/snowowl/snomed/fhir/SnomedCodeSystemApiProvider.java
> +	private CodeSystem findCodeSystemByModule(String extensionModuleId) {
It would be nice to have a few test cases that cover module-based access.

2021-05-18 11:23 UTC, merged