SO-4786: Add support for relationship concrete values
b2ihealthcare/snow-owl pull request #811
Opened 2021-05-13 16:12 UTC by apeteri

2021-05-17 12:13 UTC, apeteri commented
Ready for review; the commits added today are the results of a self-review I have personally conducted. 😄

2021-05-17 12:30 UTC, cmark requested changes

2021-05-17 12:30 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/domain/SnomedRelationshipRestSearch.java
> +	private String value;
Multi-value support?

2021-05-17 12:30 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/ecl/SnomedEclRefinementEvaluator.java
> +				.all()
To reduce memory-pressure and improve speed, use field selection here to reduce the number of fields loaded from the concrete value relationship. Same as loading fields during standard relationship search.

2021-05-17 12:30 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRelationshipSearchRequestBuilder.java
> +	public SnomedRelationshipSearchRequestBuilder filterByValue(Iterable<RelationshipValue> values) {
It is still a bit unsettled, but we have started using pluralized method names (`filterByValues`) for multi-valued filters to keep them separated from the singular versions.

2021-05-17 12:30 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedRelationshipUpdateRequest.java
> +	@Min(0)	@Max(Integer.MAX_VALUE)
A bit of inconsistency between the create and update requests. Create allows only `Byte.MAX_VALUE` while update allows `Integer.MAX_VALUE` `groups` and `unionGroups`.

2021-05-17 14:05 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/domain/SnomedRelationshipRestSearch.java
> +	private String value;
I'd keep it single valued for now. Multi-values are not great on the request level either.

2021-05-17 14:06 UTC, apeteri commented
I've made the requested changes.

2021-05-18 13:19 UTC, cmark approved these changes
LGTM!

2021-05-18 13:28 UTC, merged