SO-4731: Update ECL to version 1.5
b2ihealthcare/snow-owl pull request #837
Opened 2021-06-23 08:37 UTC by apeteri

Functionality from QL is included in the update.

2021-06-23 18:31 UTC, cmark requested changes
Looks great so far! Resolve the issues in the https://github.com/b2ihealthcare/snomed-ecl/pull/4 PR first, then here. We will merge the language PR first then this.

2021-06-23 18:31 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/META-INF/MANIFEST.MF
> + com.b2international.snomed.ecl;visibility:=reexport
I'm not seeing any version bumps for the ECL 1.5 language (in the root `pom.xml` for example). Am I missing something?

2021-07-05 09:53 UTC, cmark commented
@apeteri could you please resolve the conflict? Thanks!

2021-07-05 10:02 UTC, apeteri commented
This is the commit that introduces `com.b2international.snowowl.snomed.core.request` to the exported package list: https://github.com/b2ihealthcare/snow-owl/commit/fcf89c5074ebdfabcb9b47f028c85d102544f9c5

I haven't found anything that uses the concrete classes outside of `SnomedPlugin` (which registers them as a query optimizer / concept search request evaluator implementation) at the moment, so I have removed it along with the QL package.

2021-07-06 15:44 UTC, cmark approved these changes
LGTM!

2021-07-06 15:46 UTC, merged