SO-4898: Move snomed.languages configuration options to Resource.settings field
b2ihealthcare/snow-owl pull request #869
Opened 2021-07-30 09:56 UTC by molnarlaura

2021-07-30 10:08 UTC, apeteri requested changes

2021-07-30 10:08 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/validation/detail/SnomedValidationIssueDetailExtension.java
> +			ListMultimap<String, String> languageMap = (ListMultimap<String, String>) context.service(TerminologyResource.class).getSettings().get(SnomedTerminologyComponentConstants.CODESYSTEM_LANGUAGE_CONFI
`SnomedDescriptionUtils` sounds like a good place for a new utility method that extracts the language setting from a terminology resource when a `context` parameter is given. Please replace all occurrences of this line with such a method, it should be reachable from all places where you had to add them.

2021-07-30 10:14 UTC, apeteri commented
`snowowl.yml` configuration files for tests also need to be updated:

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.329 s <<< FAILURE! - in com.b2international.snowowl.core.rest.AllSnowOwlApiTests
com.b2international.snowowl.core.rest.AllSnowOwlApiTests  Time elapsed: 4.328 s  <<< ERROR!
java.lang.RuntimeException: Unrecognized field 'languages' in config file 'snomed'
```

2021-07-30 14:11 UTC, apeteri commented
Two issues that we have found:

- the `ObjectMapper` configured for ES indexing does not support Guava data structures such as `ListMultimap`;
- if the above is fixed by using `Map<String, List<String>>` as the type, dynamic mapping on `settings.languages` would detect each language key as a separate property with type `keyword`, leading to a mapping explosion.

This requires changing the data structure of `languages` to a `List<Entry>`, and the removed `SnomedLanguageConfig` will be re-purposed as the entry type.

2021-07-30 14:47 UTC, cmark commented
> Two issues that we have found:
> 
> * the `ObjectMapper` configured for ES indexing does not support Guava data structures such as `ListMultimap`;
> * if the above is avoided by using `Map<String, List<String>>` as the type, dynamic mapping on `settings.languages` would detect each language key as a separate property with type `keyword`, leading to a mapping explosion.
> 
> This requires changing the data structure of `languages` to a `List<Entry>`, and the removed `SnomedLanguageConfig` will be re-purposed as the entry type.

How about using a list of special objects then?

2021-07-30 15:32 UTC, molnarlaura commented
> > Two issues that we have found:
> > 
> > * the `ObjectMapper` configured for ES indexing does not support Guava data structures such as `ListMultimap`;
> > * if the above is avoided by using `Map<String, List<String>>` as the type, dynamic mapping on `settings.languages` would detect each language key as a separate property with type `keyword`, leading to a mapping explosion.
> > 
> > This requires changing the data structure of `languages` to a `List<Entry>`, and the removed `SnomedLanguageConfig` will be re-purposed as the entry type.
> 
> How about using a list of special objects then?

I will use the original `SnomedLanguageConfig` class as the special object.

2021-08-03 12:35 UTC, cmark requested changes

2021-08-03 12:35 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/SnomedConceptRestService.java
> +	@SuppressWarnings("unchecked")
Please remove this leftover annotation.

2021-08-03 12:35 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.core.rest/src/com/b2international/snowowl/snomed/core/rest/domain/SnomedConceptRestSearch.java
> +
Please remove the unnecessary whitespace changes.

2021-08-03 12:35 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/config/SnomedLanguageConfig.java
>  	public SnomedLanguageConfig(String code, String...refSetIds) {
Rename ctor argument names here as well to match the field names.

2021-08-03 12:35 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/config/SnomedLanguageConfig.java
>  		this(code, ImmutableList.copyOf(refSetIds));
Use `List.copyOf` instead.

2021-08-03 13:19 UTC, apeteri approved these changes
LGTM! Please fix the typo in the comment, and it is ready for merging.

2021-08-03 13:19 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequest.java
> +		 * Match concept descriptions where the description has language membership in on of the provided locales
Accidentally a letter.

```suggestion
		 * Match concept descriptions where the description has language membership in one of the provided locales
```

2021-08-03 13:31 UTC, cmark approved these changes

2021-08-03 13:31 UTC, merged