SO-4899 Terminology resource settings
b2ihealthcare/snow-owl pull request #886
Opened 2021-08-30 12:38 UTC by AAAlinaaa

2021-08-31 14:18 UTC, apeteri commented
Tests are failing when Snow Owl's configuration is populated:

```
java.lang.RuntimeException: Unrecognized field 'maxReasonerCount' in config file 'snomed'
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:163)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:248)
	at com.b2international.commons.config.ConfigurationFactory.resolveModuleConfigs(ConfigurationFactory.java:188)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:158)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:248)
	at com.b2international.commons.config.ConfigurationFactory.build(ConfigurationFactory.java:112)
	at com.b2international.snowowl.core.SnowOwl.createConfiguration(SnowOwl.java:240)
```

2021-09-01 10:01 UTC, apeteri requested changes
Please change setting retrievals and code system fetches in all other classes as well.

2021-09-01 10:01 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationCreateRequest.java
> +				.get(0);
The currently accessed `TerminologyResource` should be available from the context; it is loaded early on during the execution of a request:

```suggestion
		CodeSystem codeSystem = (CodeSystem) context.service(TerminologyResource.class);
```

2021-09-01 10:01 UTC, apeteri commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationCreateRequest.java
> +				: SnomedCoreConfiguration.DEFAULT_MAXIMUM_REASONER_COUNT;
Most of these lookups would benefit from `Map.getOrDefault(key, defaultValue)`:

```suggestion
		int maxReasonerCount = codeSystem.getSettings().getOrDefault(
			SnomedCoreConfiguration.MAXIMUM_REASONER_COUNT,
			SnomedCoreConfiguration.DEFAULT_MAXIMUM_REASONER_COUNT);
```

2021-10-06 09:42 UTC, cmark requested changes

2021-10-06 09:42 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/config/SnomedCoreConfiguration.java
> +	public static final String DEFAULT_NAMESPACE_AND_MODULE_ASSIGNER = "default";
Move these to the class `com.b2international.snowowl.snomed.common.SnomedTerminologyComponentConstants` to be next to the other config keys and default values.

2021-10-06 09:42 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/SnomedReasonerPlugin.java
> +import com.b2international.snowowl.snomed.reasoner.index.ClassificationTaskDocument;
Configure your IDE automatic wildcard import setting and revert this change, please.

2021-10-06 09:42 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/classification/ClassificationTracker.java
> +
Whitespace changes only, please revert.

2021-10-06 09:42 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationCreateRequest.java
> +
Same here.

2021-10-06 09:42 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationJobRequest.java
> +		final boolean concreteDomainSupported = true;
Hardcoded `true` value, please fix.

2021-10-06 09:42 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/OntologyExportRequest.java
> +		final boolean concreteDomainSupportEnabled = true;
Same here.

2021-10-06 09:42 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/SaveJobRequest.java
> +import com.b2international.snowowl.snomed.datastore.request.IdRequest;
Revert import changes to wildcard import, please.

2021-10-06 09:42 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/codesystem/CodeSystem.java
> +	public static final String DEFAULT_REFSET_MODULE_ID = "defaultRefsetModuleId";
These are already defined in the `SnomedTerminologyComponentConstants` class, please remove them.

2021-10-07 14:16 UTC, cmark requested changes

2021-10-07 14:16 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/config/SnomedCoreConfiguration.java
> +	public static final String MAXIMUM_REASONER_RUNS = "maxReasonerRuns";
If these are SNOMED CodeSystem configuration keys, then move them to the SnomedTerminologyComponentConstants class as well. The same applies to their default values.

2021-10-07 14:16 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/ClassificationJobRequest.java
> +		final Set<String> reasonerExcludedModuleIds = (Set<String>) resource.getSettings().getOrDefault(REASONER_EXCLUDE_MODULE_IDS, Collections.emptySet());
It would be better to treat the value as an Iterable and not a Set. The deserialized Collection might be a List or something else in this case, so this could generate unwanted CCEs runtime. Use `Collection3.toImmutableSet()` to convert the value to an ImmutableSet.

2021-10-07 14:16 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.reasoner/src/com/b2international/snowowl/snomed/reasoner/request/OntologyExportRequest.java
> +		final Set<String> reasonerExcludedModuleIds = (Set<String>) resource.getSettings()
Same applies here.

2021-10-08 09:28 UTC, cmark approved these changes
LGTM!

2021-10-08 09:28 UTC, cmark commented on snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/config/SnomedCoreConfiguration.java
> +	public static final String MAXIMUM_REASONER_RUNS = "maxReasonerRuns";
Please remove this key.

2021-10-08 09:30 UTC, apeteri approved these changes

2021-10-08 09:31 UTC, merged