SO-4945: Improve Suggestions API
b2ihealthcare/snow-owl pull request #921
Opened 2021-10-14 16:00 UTC by molnarlaura

2021-10-14 16:19 UTC, cmark requested changes

2021-10-14 16:19 UTC, cmark commented on core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/suggest/SuggestRestService.java
> +		if (params.getMinOccurrenceCount() != null) {
Please set the `minOccurenceCount` only once.

2021-10-14 16:19 UTC, cmark commented on core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/suggest/SuggestRestService.java
> +		if (body.getMinOccurrenceCount() != null) {
Same here.

2021-10-14 16:19 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptSuggestionRequest.java
> +			termFilter = TermFilter.minTermMatch(getString(TERM), minOccurrenceCount).withIgnoreStopwords();
Convert the `minOccurenceCount` to a key and make sure it is set to the default three value when it is not set and base term is not given.

2021-10-15 08:23 UTC, molnarlaura commented on core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/suggest/SuggestRestService.java
> +		if (params.getMinOccurrenceCount() != null) {
Done

2021-10-15 08:23 UTC, molnarlaura commented on core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/suggest/SuggestRestService.java
> +		if (body.getMinOccurrenceCount() != null) {
Done

2021-10-15 08:23 UTC, molnarlaura commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/ConceptSuggestionRequest.java
> +			termFilter = TermFilter.minTermMatch(getString(TERM), minOccurrenceCount).withIgnoreStopwords();
Done

2021-10-15 10:55 UTC, cmark approved these changes
LGTM!

2021-10-15 10:55 UTC, merged