SO-4662: Migrate MRCM validation to 8.x and new MRCM refset format
b2ihealthcare/snow-owl pull request #930
Opened 2021-10-22 13:47 UTC by AAAlinaaa

2021-10-26 19:11 UTC, apeteri requested changes

2021-10-26 19:11 UTC, apeteri commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +		final String previousContentType = contentTypes.get(typeId);
No other part of the code seems to be interested in `previousContentType`. Can it and `contentTypes` be removed altogether?

2021-10-26 19:11 UTC, apeteri commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +			ancestorIds.add(ancestorId);
Concept-and-subtypes could add the SCTID to `conceptIds`...

2021-10-26 19:11 UTC, apeteri commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +		.filter(SnomedConceptDocument.Expressions.ids(destinationIds));
...then `destinationIds` can be made smaller by removing `conceptIds` from it before adding it to this query...

2021-10-26 19:11 UTC, apeteri commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +	incorrectDestinationIds.removeAll(ancestorIds);
...and these two rows are no longer necessary.

2021-10-26 19:11 UTC, apeteri commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +	//Find OWL axiom members with relationships that have destinations out of the allowed range
This comment should be about looking for "real" relationships, not relationships on OWL axiom members. The duplicate comment below is in the right spot.

2021-10-26 19:11 UTC, apeteri commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +final String attributeRangeRefset = Concepts.REFSET_MRCM_ATTRIBUTE_RANGE_INTERNATIONAL;
This reference set ID ended up being unused.

2021-10-26 19:11 UTC, apeteri commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint_type.groovy
> +final String attributeRefset = Concepts.REFSET_MRCM_ATTRIBUTE_DOMAIN_INTERNATIONAL;
In this script the attribute reference set ID is unused.

2021-10-26 19:50 UTC, cmark requested changes
It looks promising. Please fix @apeteri suggested fixes first, then mine. 🙇

2021-10-26 19:50 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +			println "Could not parse clause ${clause}";
It would be nice to log these properly with ctx.log() instead of just to sysout. Also, make sure you log the exception as well with the errors, so we know if an MRCM constraint has invalid ECL.

2021-10-26 19:50 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +		if (clause.contains("<<")) {
What about any other basic operator support here? Like child IDs and memberOf. I expect at least those two to come up in MRCM constraints in the future.

2021-10-26 19:50 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint_type.groovy
> +		.filter(EclExpression.of(conceptSetExpression, Trees.INFERRED_FORM).resolveToExpression(ctx).getSync())
Make sure you always specify a timeout value when you perform something async but wait for the results sync. That is crucial in backend development.

2021-10-26 19:50 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint_type.groovy
> +		.filter(EclExpression.of(conceptSetExpression, Trees.INFERRED_FORM).resolveToExpression(ctx).getSync())
Also, you can directly use the expression returned from the `resolveToExpression()` call, no need to wrap it in a boolean query.

2021-10-26 19:50 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint_type.groovy
> +searchRelationships(false);
It would be nice to document the boolean flag here and the temporal coupling between the statements in lines 255-258. Future maintainers of this code will thank you for it. :)

2021-10-26 19:50 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/test/java/com/b2international/snowowl/validation/snomed/GenericValidationRuleTest.java
>  	public void rule_mrcm_constraint() throws Exception {
I would love to see a bit more unit tests for the new MRCM rule implementations. It looks fast and probably it is fast enough, but is it accurate enough? Please consider including a few official examples or similar ones as test cases with a few concepts and relationships as test data just to verify the results. Also, did you run the rules on any official SNOMED content? INT? UK? Could you please share the results with us?

2021-10-28 06:56 UTC, AAAlinaaa commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +		if (clause.contains("<<")) {
Maybe. For now, non-concrete-domain range constraints are either self ids, descendants of, or self and descendants of.

2021-10-28 08:28 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +		if (clause.contains("<<")) {
I know, but to make the tool a bit more future-proof, those two could be added quickly and easily. Could you please make the necessary changes? 🙇

2021-10-28 12:26 UTC, AAAlinaaa commented on snomed/com.b2international.snowowl.validation.snomed/src/test/java/com/b2international/snowowl/validation/snomed/GenericValidationRuleTest.java
>  	public void rule_mrcm_constraint() throws Exception {
Yes, I have run MRCM validation on both INT and UK datasets, albeit only with the INT rules since others are not yet converted to the new format. Run times ranged between 20 and 27 seconds on all.

2021-10-29 09:11 UTC, cmark approved these changes
LGTM!

2021-10-29 09:11 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/test/java/com/b2international/snowowl/validation/snomed/GenericValidationRuleTest.java
>  	public void rule_mrcm_constraint() throws Exception {
Sounds great! Thanks!

2021-10-29 09:12 UTC, cmark commented on snomed/com.b2international.snowowl.validation.snomed/src/main/resources/scripts/rule_mrcm_constraint.groovy
> +		if (clause.contains("<<")) {
Thanks for adding them! 🙇

2021-10-29 09:14 UTC, apeteri approved these changes

2021-10-29 09:24 UTC, merged