Support index-level request caching
b2ihealthcare/snow-owl pull request #931
Opened 2021-10-25 15:44 UTC by cmark

This PR introduces index-level search request caching and potential configuration on request API level via [cacheHits(ServiceProvider)](https://github.com/b2ihealthcare/snow-owl/commit/163181e3982809171ef740013a72e73df31174d3#diff-b854641ff991e8157af0c445f61bebd4c94474b2434c9ac8ae2bb8c4d1fce435R157).
By default the system will cache:
* all requests that are being executed on versioned content
* certain ECL search requests (or partial ECL search requests)

2021-10-25 18:57 UTC, apeteri requested changes

2021-10-25 18:57 UTC, apeteri commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchIndexResourceRequest.java
> +		return Revision.class.isAssignableFrom(getFrom()) && context.optionalService(PathWithVersion.class).isPresent();
`PathWithVersion` does not always contain a version URI; when the original request path does not correspond to a version identifier, eg. when it contains a branch separator character, only an absolute branch path will be returned from the resolver: https://github.com/b2ihealthcare/snow-owl/blob/eb3e28d471f2e18dd1a7455691bfdbfb1d32caca/core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/uri/DefaultResourceURIPathResolver.java#L76-L80

2021-10-26 07:14 UTC, nagyo requested changes

2021-10-26 07:14 UTC, nagyo commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchIndexResourceRequest.java
> +		return Revision.class.isAssignableFrom(getFrom()) && context.optionalService(PathWithVersion.class).isPresent();
I agree, it would be nice to introduce a more rigorous condition for this, given that it is quite hard to validate if a search result is indeed correct when it was cached.

2021-10-26 12:50 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchIndexResourceRequest.java
> +		return Revision.class.isAssignableFrom(getFrom()) && context.optionalService(PathWithVersion.class).isPresent();
I'm open to any suggestions. This was the easiest way at the moment to determine whether a request is being executed on a version or not (and I think it's not that bad 😅).

2021-10-26 12:59 UTC, cmark commented on core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/SearchIndexResourceRequest.java
> +		return Revision.class.isAssignableFrom(getFrom()) && context.optionalService(PathWithVersion.class).isPresent();
@apeteri see this piece of code, the PathWithVersion instance gets injected only when it has a version URI:
https://github.com/b2ihealthcare/snow-owl/pull/931/files#diff-a4877e9655543b6f3a4aeb80fb2df33cfb521470f823c273b36214aad0b087ecR47

2021-10-26 13:09 UTC, apeteri approved these changes

2021-10-26 13:24 UTC, nagyo approved these changes
👍🏻

2021-10-26 13:26 UTC, merged